Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,8 +17,9 @@ jobs:
         python-version: ["3.10","3.11"]
     
     env:
-      ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections 
+      ANSIBLE_COLLECTIONS_PATH: ~/.ansible/collections
       ANSIBLE_ROLES_PATH: ~/.ansible/roles
+      PYTHON_BIN_PATH: /opt/hostedtoolcache/Python/${{ matrix.python-version }}/x64/bin 
 
     steps:
       - name: Checkout code
@@ -32,21 +33,22 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install ansible molecule molecule-vagrant
-
-          # Path donde se instala
-          COLLECTIONS_DIR="${HOME}/.ansible/collections"
           
-          # Forzar instalacion a path
-          ansible-galaxy collection install community.general --force -p "${COLLECTIONS_DIR}"
-          ansible-galaxy install geerlingguy.mysql geerlingguy.php -p "${HOME}/.ansible/roles"
+          "${PYTHON_BIN_PATH}/pip" install ansible molecule molecule-vagrant
+          "${PYTHON_BIN_PATH}/ansible-galaxy" collection install community.general --force
+          "${PYTHON_BIN_PATH}/ansible-galaxy" install geerlingguy.mysql geerlingguy.php -p "${HOME}/.ansible/roles"
 
-          # Debug final
-          echo "Debugging collection path: ${COLLECTIONS_DIR}/ansible_collections/community/general/"
-          ls -la "${COLLECTIONS_DIR}/ansible_collections/community/general/" || echo "FATAL: Collection still not found after explicit install attempt."
+          # paths finales
+          echo "Path for collections: ${ANSIBLE_COLLECTIONS_PATH}"
+          echo "Path for roles: ${ANSIBLE_ROLES_PATH}"
+          echo "Path for Python binaries: ${PYTHON_BIN_PATH}"
           
-          echo "Listing contents of ${COLLECTIONS_DIR}/ansible_collections/"
-          ls -la "${COLLECTIONS_DIR}/ansible_collections/"
+          # Por las dudas debug del colection path
+          echo "Debugging collection path: ${ANSIBLE_COLLECTIONS_PATH}/ansible_collections/community/general/"
+          ls -la "${ANSIBLE_COLLECTIONS_PATH}/ansible_collections/community/general/" || echo "FATAL: Collection still not found after explicit install attempt."
+          
+          echo "Listing contents of ${ANSIBLE_COLLECTIONS_PATH}/ansible_collections/"
+          ls -la "${ANSIBLE_COLLECTIONS_PATH}/ansible_collections/"
 
       - name: Install Vagrant
         run: |
@@ -56,4 +58,4 @@ jobs:
       - name: Run Molecule tests
         working-directory: ./
         run: |
-          molecule test
+          PATH="${PYTHON_BIN_PATH}:${PATH}" molecule test
